name: Build and push Docker Image

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v4

      - name: login to GHCR
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin

      - name: Build and push Image
        run: |
          docker build -t ghcr.io/${{ secrets.GH_USERNAME }}/fastapi-app:latest .
          docker push ghcr.io/${{ secrets.GH_USERNAME }}/fastapi-app:latest